language: bash
before_install:
    - gem install fakes3
    - sudo apt-get update && sudo apt-get install -y python-setuptools && wget http://downloads.sourceforge.net/project/s3tools/s3cmd/1.5.2/s3cmd-1.5.2.tar.gz && tar xvfz s3cmd-1.5.2.tar.gz && cd s3cmd-1.5.2 && sudo python setup.py install
script:
    - bash tests/test.sh